type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product
  description:
    type: string
    description: Product description
  price:
    type: string
    format: '^[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$'
    description: Product price
  cost:
    type: string
#    format: '^[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$'
    format: '^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$'
    description: Product cost
  created:
    type: string
    format: date-time
    description: Date when product was created
  modified:
    type: string
    format: date-time
    description: Date when product was modified
  categories:
    type: array
    items:
      $ref: './Category.yaml'
  dimensions:
    $ref: './Dimensions.yaml'
  images:
    type: array
    items:
      $ref: './Image.yaml'