get:
  tags:
    - Product
  summary: Get list of products
  description: Get list of products (ordered by name)
  operationId: getProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/Products.yaml'
    '400':
      description: Bad request
    '404':
      description: User not found
      $ref: '../../components/responses/Problem.yaml'
