get:
  tags:
    - Product
  summary: Get product by id
  description: Get product by id
  operationId: getProductById
  parameters:
    - $ref: '../../components/parameters/uuid_id.yaml'
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/Product.yaml'
    '400':
      description: Bad request
    '404':
      description: Product not found
      $ref: '../../components/responses/Problem.yaml'
put:
  tags:
    -  Product
  summary: Update a product by ID
  description: Update a product by ID
  operationId: updateProduct
  parameters:
    - $ref: '../../components/parameters/uuid_id.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/v1/product_update.yaml'
  responses:
    '200':
      description: Product updated
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/Product.yaml'
    '400':
      description: Bad Request
    '404':
      description: Not Found
      $ref: '../../components/responses/Problem.yaml'
delete:
  tags:
    - Product
  summary: Delete product by id
  description: Delete product by id
  operationId: deleteProduct
  parameters:
    - $ref: '../../components/parameters/uuid_id.yaml'
  responses:
    '204':
      description: No content
    '400':
      description: Bad request
    '404':
      description: Product not found
      $ref: '../../components/responses/Problem.yaml'