get:
  tags:
    - Product
  summary: Get product by id
  description: Get product by id
  operationId: getProductById
  parameters:
    - name: id
      in: path
      description: The id of product to retrieve.
      required: true
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/Product.yaml'
    '400':
      description: Bad request
    '404':
      description: User not found
      $ref: '../../components/responses/Problem.yaml'
